var hedges = [
  { "name": "Systematic Reviews",
    "term": "systematic [sb]" },
  { "name": "Diagnosis (broad)",
    "term": "Diagnosis/Broad[filter]" },
  { "name": "Diagnosis (narrow)",
    "term": "Diagnosis/Narrow[filter]" },
  { "name": "Etiology (broad)",
    "term": "Etiology/Broad[filter]" },
  { "name": "Etiology (narrow)",
    "term": "Etiology/Narrow[filter]" },
  { "name": "Prognosis (broad)",
    "term": "Prognosis/Broad[filter]" },
  { "name": "Prognosis (narrow)",
    "term": "Prognosis/Narrow[filter]" },
  { "name": "Therapy (broad)",
    "term": "Therapy/Broad[filter]" },
  { "name": "Therapy (narrow)",
    "term": "Therapy/Narrow[filter]" },
  { "name": "Clinical Prediction Guides (broad)",
    "term": "Clinical Prediction Guides/Broad[filter]" },
  { "name": "Clinical Prediction Guides (narrow)",
    "term": "Clinical Prediction Guides/Narrow[filter]" },
]
