var hedges = [
  { "name": "Systematic Reviews",
    "term": "systematic [sb]" },
  { "name": "Diagnosis (broad)",
    "term": "Diagnosis/Broad[filter]" },
  { "name": "Diagnosis (narrow)",
    "term": "Diagnosis/Narrow[filter]" },
  { "name": "Etiology (broad)",
    "term": "Etiology/Broad[filter]" },
  { "name": "Etiology (narrow)",
    "term": "Etiology/Narrow[filter]" },
  { "name": "Prognosis (broad)",
    "term": "Prognosis/Broad[filter]" },
  { "name": "Prognosis (narrow)",
    "term": "Prognosis/Narrow[filter]" },
  { "name": "Therapy (broad)",
    "term": "Therapy/Broad[filter]" },
  { "name": "Therapy (narrow)",
    "term": "Therapy/Narrow[filter]" },
  { "name": "Clinical Prediction Guides (broad)",
    "term": "Clinical Prediction Guides/Broad[filter]" },
  { "name": "Clinical Prediction Guides (narrow)",
    "term": "Clinical Prediction Guides/Narrow[filter]" },
  { "name": "Qualitative",
    "term": "interview*[Title/Abstract] OR interviews[MeSH:noexp] OR experience*[Text Word] OR qualitative[Title/Abstract]" },
  { "name": "Costs",
    "term": "'costs and cost analysis'[MeSH Term] OR costs[Title/Abstract] OR cost effective*[Title/Abstract]" },
  { "name": "Economics ",
    "term": "cost*[Title/Abstract] OR 'costs and cost analysis'[MeSH:noexp] OR cost benefit analys*[Title/Abstract] OR cost-benefit analysis[MeSH Term] OR health care costs[MeSH:noexp]" },
]
